name: Build and deploy Node.js app to Azure Web App - nobrokerage-chatbot-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # FIXED: Change to backend directory before npm install
      - name: npm install, build, and test
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      # FIXED: Upload only the backend folder
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1E3992A147C74CB8BA00CF164F27CE0D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_66B5511610CC4D5F91446B096BBA91E6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C518B21B8A44DF2B21554625A4AFB27 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nobrokerage-chatbot-backend'
          slot-name: 'Production'
          package: .
